"""Create database

Revision ID: b71d6431feee
Revises: 
Create Date: 2025-04-06 20:39:54.648716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b71d6431feee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('name', name=op.f('uq_user_name'))
    )
    op.create_table('user_passes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hash_pass', sa.String(), nullable=False),
    sa.Column('date_pass', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_passes_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_passes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_passes')
    op.drop_table('user')
    # ### end Alembic commands ###
