"""upgrade auth tables

Revision ID: 498c3f6958bd
Revises: e0a6453e1b97
Create Date: 2025-03-22 16:38:50.377585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '498c3f6958bd'
down_revision: Union[str, None] = 'e0a6453e1b97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('user_passes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hash_pass', sa.String(), nullable=False),
    sa.Column('date_pass', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_passes_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_passes'))
    )
    op.add_column('user', sa.Column('name', sa.String(), nullable=False))
    op.drop_constraint('uq_user_login', 'user', type_='unique')
    op.drop_constraint('uq_user_password', 'user', type_='unique')
    op.create_unique_constraint(op.f('uq_user_name'), 'user', ['name'])
    op.drop_column('user', 'login')
    op.drop_column('user', 'password')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('uq_user_name'), 'user', type_='unique')
    op.create_unique_constraint('uq_user_password', 'user', ['password'])
    op.create_unique_constraint('uq_user_login', 'user', ['login'])
    op.drop_column('user', 'name')
    op.drop_table('user_passes')
    # ### end Alembic commands ###
